# Generated by Django 5.1.4 on 2025-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarkform',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
